### PR TITLE
add systray function + instance handling

### PR DESCRIPTION
**Pull request by seathasky**
adds icon to systray when closed and allows to show app from systray icon.

### CODE REVIEW

**Comment by seathasky** [comment]
Was working out some issues on this but should be clean to merge if you like the feature.

Here it is in action:


https://github.com/user-attachments/assets/2ce2d6ec-6ac1-4ab3-96e2-d6974fa2b6ba

**Comment by seathasky** [comment]
Sorry for the messy PR, was fixing minor issues. Should be good now!

**Comment by seathasky** [comment]
Alright, all changed made in this PR:


https://github.com/user-attachments/assets/05f37610-8eeb-4f7f-b69d-072c571a31d2

**Comment by seathasky** [comment]
https://github.com/user-attachments/assets/139cd691-9c9d-482d-b337-4a9e71a6691f

**Review by theAbdoSabbagh — APPROVED** [review]

**Comment by theAbdoSabbagh** [comment]
Thank you for the PR, looks good! Although I think its better if we eventually put the icon in the appdata path, but doesnt matter much for now

**Comment by seathasky** [comment]
> Thank you for the PR, looks good! Although I think its better if we eventually put the icon in the appdata path, but doesnt matter much for now

Roger that! I'm still pretty new to coding in general so feel free to help anywhere you can. Honestly not sure how to add stuff to appdata yet but very interested to learn. Thanks for merging

**Comment by theAbdoSabbagh** [comment]
> > Thank you for the PR, looks good! Although I think its better if we eventually put the icon in the appdata path, but doesnt matter much for now
> 
> Roger that! I'm still pretty new to coding in general so feel free to help anywhere you can. Honestly not sure how to add stuff to appdata yet but very interested to learn. Thanks for merging

For someone new to coding you did a really good job. Honestly I don't think I'll be doing that much work on the app, since it doesnt seem like theres many people interested in it in the first place, and im also working on a personal project for my university atm

**Comment by seathasky** [comment]
Its no worry if you don't work on it right away. I think it needs time to garner interest, I don't mind doing small things to enhance things for the time being. Mainly Ui stuffs. Maybe you will get more interested over time if you see others contributing. Either way, I think the application has potential and hope to see you continue adding to it eventually.

**Pull request merged**
